sequenceDiagram
    actor S as Product Manage Staff
    participant EIV as :ExcelImportView
    participant EIC as :ExcelController
    participant PM as :ProductModel

    activate S
    S->>EIV: Click upload file button
    activate EIV
    EIV-->>S: File chooser opened
    deactivate EIV

    S->>EIV: Select file
    activate EIV

    EIV->>EIC: Upload file
    activate EIC
    EIC->>EIC: Parse file
    opt if file is not valid (type, size)
        EIC-->>EIV: Return error
        EIV-->>S: Show error message
    end

    loop for each row in file
        EIC->>EIC: Validate row

        alt row is valid
            EIC->>PM: Save product
            activate PM
            PM-->>EIC: Return status
            deactivate PM
        else row is not valid & stop on error
            EIC->>EIC: Log error and stop
            EIC-->>EIV: Return error
            EIV-->>S: Show error message
        else row is not valid & continue on error
            EIC->>EIC: Log error and continue
        end
    end

    alt if no error
        EIC-->>EIV: Return success status
        EIV-->>S: Show success message
    else if errors exist
        EIC-->>EIV: Return error message
        EIV-->>S: Show error message
    end

    deactivate EIC

    deactivate EIV
    deactivate S
