sequenceDiagram
    actor S as Warehouse Staff
    participant IPV as :ImportProductView
    participant IPC as :ImportProductController
    participant PC as :ProductController
    participant SIM as :StockImportModel
    participant P as :ProductModel

    loop until no more products to import
        S->>IPV: Find product by name
        activate IPV
        IPV->>PC: Find product by name
        PC-->>IPV: Return product list
        IPV-->>S: Return product list
        deactivate IPV

        S->>IPV: Select product
        activate IPV
        IPV->>IPV: Add to selected products
        IPV-->>S: Confirm added
        deactivate IPV
    end

    S->>IPV: Submit import request button click
    activate IPV
    IPV->>IPC: Submit import request
    activate IPC
    IPC->>P: Add to quantity
    P-->>IPC: Return status
    IPC->>SIM: Insert new stock import card
    SIM-->>IPC: Return status
    IPC-->>IPV: Return status
    deactivate IPC
    IPV->>IPV: Check return status
    alt success
        IPV->>S: Show success message
    else error
        IPV->>S: Show error message
    end
    deactivate IPV


    
